server:
  port: 8082

spring:
  application:
    name: client-api
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 3000
            read-timeout: 5000

app:
  gateway-api:
    base-url: http://${GATEWAY_API_HOST:localhost}:8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.demo.client: DEBUG
