server:
  port: 8081

spring:
  application:
    name: balance-api
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:balance}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.demo.balance: DEBUG
